import { ExpLogo } from "@/interfaces/expLogo.interface";

import {
  SiExpress,
  SiHtml5,
  SiCss3,
  SiJavascript,
  SiTypescript,
  SiPython,
  SiC,
  SiReact,
  SiNodedotjs,
  SiNextdotjs,
  SiNestjs,
  SiSwagger,
  SiPostman,
  SiDocker,
  SiFigma,
  SiGit,
  SiTailwindcss,
  SiGithub,
  SiMysql,
  SiMongodb,
  SiPrisma,
  SiGraphql,
  SiApollographql,
} from "react-icons/si";
import { FaJava } from "react-icons/fa";
import { PiFileSql } from "react-icons/pi";

export const experienceLogoList: ExpLogo[] = [
  {
    name: "HTML5",
    icon: SiHtml5,
    type: "language",
    color: "#E34F26",
  },
  {
    name: "CSS",
    icon: SiCss3,
    type: "language",
    color: "#1572B6",
  },
  {
    name: "TailwindCss",
    icon: SiTailwindcss,
    type: "framework",
    color: "#06B6D4",
  },
  {
    name: "Javascript",
    icon: SiJavascript,
    type: "language",
    color: "#F7DF1E",
  },
  {
    name: "Typescript",
    icon: SiTypescript,
    type: "language",
    color: "#3178C6",
  },
  {
    name: "Python",
    icon: SiPython,
    type: "language",
    color: "#3776AB",
  },
  {
    name: "Java",
    icon: FaJava,
    type: "language",
    color: "#F89820",
  },
  {
    name: "C/C++",
    icon: SiC,
    type: "language",
    color: "#A8B9CC",
  },
  {
    name: "React.js",
    icon: SiReact,
    type: "framework",
    color: "#61DAFB",
  },
  {
    name: "Node.js",
    icon: SiNodedotjs,
    type: "framework",
    color: "#339933",
  },
  {
    name: "Next.js",
    icon: SiNextdotjs,
    type: "framework",
    color: "#000000",
  },
  {
    name: "Nest.js",
    icon: SiNestjs,
    type: "framework",
    color: "#E0234E",
  },
  {
    name: "Express.js",
    icon: SiExpress,
    type: "framework",
    color: "#000000",
  },
  {
    name: "SQL/NoSQL",
    icon: PiFileSql,
    type: "language",
    color: "#4479A1",
  },
  {
    name: "Swagger",
    icon: SiSwagger,
    type: "framework",
    color: "#85EA2D",
  },
  {
    name: "Postman",
    icon: SiPostman,
    type: "tool",
    color: "#FF6C37",
  },
  // {
  //   name: "Docker",
  //   icon: SiDocker,
  // },
  {
    name: "Figma",
    icon: SiFigma,
    type: "tool",
    color: "#F24E1E",
  },
  {
    name: "Git",
    icon: SiGit,
    type: "tool",
    color: "#F05032",
  },
  {
    name: "Github",
    icon: SiGithub,
    type: "tool",
    color: "#181717",
  },
  {
    name: "MySQL",
    icon: SiMysql,
    type: "tool",
    color: "#4479A1",
  },
  {
    name: "Prisma",
    icon: SiPrisma,
    type: "tool",
    color: "#2D3748",
  },
  {
    name: "MongoDB",
    icon: SiMongodb,
    type: "tool",
    color: "#47A248",
  },
  // {
  //   name: "GraphQl",
  //   icon: SiGraphql,
  //   type: "tool",
  // },
  // {
  //   name: "GraphQl",
  //   icon: SiApollographql,
  // },
];
